"""
Keep all OS env used.
"""
import os

from .defaults import PREFIX

# pylint: disable=line-too-long
# :start: TCR
TCR_HOST = os.getenv(PREFIX + "_TCR_HOST")
# :end: TCR

TCR_CLIENT_CLI_PY_TYPE = os.getenv(PREFIX + "_TCR_CLIENT_PY_TYPE")
TCR_CLIENT_CLI_PY_SCRIPT_PATH = os.getenv(PREFIX + "_TCR_CLIENT_PY_SCRIPT_PATH")
TCR_CLIENT_CLI_PY_DOCKER_IMAGE = os.getenv(PREFIX + "_TCR_CLIENT_PY_DOCKER_IMAGE")

TCR_CLIENT_CLI_JS_TYPE = os.getenv(PREFIX + "_TCR_CLIENT_JS_TYPE")
TCR_CLIENT_CLI_JS_SCRIPT_PATH = os.getenv(PREFIX + "_TCR_CLIENT_JS_SCRIPT_PATH")
TCR_CLIENT_CLI_JS_DOCKER_IMAGE = os.getenv(PREFIX + "_TCR_CLIENT_JS_DOCKER_IMAGE")

TCR_CLIENT_CLI_JAVA_TYPE = os.getenv(PREFIX + "_TCR_CLIENT_JAVA_TYPE")
TCR_CLIENT_CLI_JAVA_JAR_PATH = os.getenv(PREFIX + "_TCR_CLIENT_JAVA_JAR_PATH")
TCR_CLIENT_CLI_JAVA_DOCKER_IMAGE = os.getenv(PREFIX + "_TCR_CLIENT_JAVA_DOCKER_IMAGE")

TCR_CLIENT_CLI_GO_SCRIPT_PATH = os.getenv(PREFIX + "_TCR_CLIENT_GO_SCRIPT_PATH")

# :start: TSPA
TSPA_HOST = os.getenv(PREFIX + "_TSPA_SERVER_HOST")
TSPA_KEYCLOAK_URL = os.getenv(PREFIX + "_TSPA_KEYCLOAK_URL") or ""
TSPA_KEYCLOAK_REALM = os.getenv(PREFIX + "_TSPA_KEYCLOAK_REALM") or ""
TSPA_KEYCLOAK_CLIENT_ID = os.getenv(PREFIX + "_TSPA_KEYCLOAK_CLIENT_ID") or ""
TSPA_KEYCLOAK_CLIENT_SECRET = os.getenv(PREFIX + "_TSPA_KEYCLOAK_CLIENT_SECRET") or ""
TSPA_KEYCLOAK_SCOPE = os.getenv(PREFIX + "_TSPA_KEYCLOAK_SCOPE") or ""
# :end: TSPA

# :start: ZM
ZM_HOST = os.getenv(PREFIX + "_DNS_ZM_SERVER_HOST") or ""
ZM_KEYCLOAK_URL = os.getenv(PREFIX + "_ZM_KEYCLOAK_URL") or ""
ZM_KEYCLOAK_REALM = os.getenv(PREFIX + "_ZM_KEYCLOAK_REALM") or ""
ZM_KEYCLOAK_CLIENT_ID = os.getenv(PREFIX + "_ZM_KEYCLOAK_CLIENT_ID") or ""
ZM_KEYCLOAK_CLIENT_SECRET = os.getenv(PREFIX + "_ZM_KEYCLOAK_CLIENT_SECRET") or ""
ZM_KEYCLOAK_SCOPE = os.getenv(PREFIX + "_ZM_KEYCLOAK_SCOPE") or ""
# :end: ZM

# pylint: enable=line-too-long
