- name: Install Python on MacOSX
  homebrew:
    name: '{{ item }}'
    state: present
  with_items:
    - python
  when: ansible_distribution == 'MacOSX'
  tags:
    - MacOSX
    - py

- name: Install Python on Ubuntu
  apt:
    name:
      - python3-dev
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
  when: ansible_distribution == 'Ubuntu'
  become: true
  become_method: sudo
  tags:
    - Ubuntu
    - py

- name: "Add Python to shell config file `~/.trainrc`"
  lineinfile:
    dest: ~/.trainrc
    state: present
    line: "{{ item }}"
    create: true
  with_items:
    - "# TRAIN ansible: python config"
    - "export PYENV_ROOT=~/.pyenv"
    - "export PATH=$PYENV_ROOT/bin:$PATH"
    - "eval \"$(pyenv init -)\""
  tags:
    - py

- name: Install concrete version for python
  ansible.builtin.shell: "source ~/.trainrc && {{ item }}"
  with_items:
    # speedup pyenv commands
    - cd ~/.pyenv && src/configure && make -C src
    - pyenv --version
    - pyenv install 3.11.4
    - pyenv global 3.11.4
  args:
    executable: /bin/bash
  tags:
    - py
