@startuml

actor "BDD-Steps"
participant "TSPA Server"
participant "DNS Zone Manager Server"


"BDD-Steps" --> "TSPA Server": create new pointer

activate "TSPA Server"
"TSPA Server" --> "DNS Zone Manager Server": .publishTrustSchemes(frameworkName, data)
"TSPA Server" --> "TSPA Server": storeTrustService(frameworkName, data)
deactivate "TSPA Server"


@enduml


